version: '3'
services:
  dns:
    image: jrcichra/lancachenet-lancache-dns:latest  ## Pulling DNS server for arm
    env_file: .env
#    ports:
#      - ${DNS_BIND_IP}:53:53/udp
#      - ${DNS_BIND_IP}:53:53/tcp
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    restart: always
#  sniproxy:
#    image: jrcichra/lancachenet-sniproxy:latest  ## Pulling Sniproxy for arm
#    env_file: .env
#    ports:
#    #  - 443:443/tcp
#      - 192.168.1.214:443:443/tcp
#      - 192.168.1.215:443:443/tcp
#      - 192.168.1.216:443:443/tcp
#      - 192.168.1.217:443:443/tcp
#      - 192.168.1.218:443:443/tcp
#      - 192.168.1.219:443:443/tcp
#      - 192.168.1.220:443:443/tcp
#      - 192.168.1.221:443:443/tcp
#      - 192.168.1.222:443:443/tcp
#    networks:
#      static-network:
#        ipv4_address: 172.20.128.3
#    restart: always
  monolithic:
    image: jrcichra/lancachenet-monolithic:latest ## Pulling monolithic for arm
    env_file: .env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: always
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    env_file: .env
    ports:
      - 192.168.1.213:53:53/tcp
      - 192.168.1.213:53:53/udp
    # - 784:784/udp
    # - 853:853/tcp
      - 3000:3000/tcp
    # - 81:80/tcp
    # - 443:443/tcp
    volumes:
      - ${ADGUARD_ROOT}:/opt/adguardhome/work
      - ${ADGUARD_ROOT}:/opt/adguardhome/conf
    networks:
      static-network:
        ipv4_address: 172.20.128.4
    restart: always
  unbound:
    image: mvance/unbound-rpi:latest
    container_name: unbound
    env_file: .env
    ports:
      - 5335:53/tcp
      - 5335:53/udp
    volumes:
      - ${UNBOUND_ROOT}:/opt/unbound/etc/unbound/
      - ${UNBOUND_ROOT}:/opt/unbound/etc/unbound/forward-records.conf
      - ${UNBOUND_ROOT}:/opt/unbound/etc/unbound/srv-records.conf
      - ${UNBOUND_ROOT}:/opt/unbound/etc/unbound/a-records.conf
    networks:
      static-network:
        ipv4_address: 172.20.128.5
    restart: always
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          #ip_range: 172.28.5.0/24
